inherit_from: ../.rubocop.yml

Layout/LineLength:
  Max: 170

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Max: 100

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Exclude:
    - 'cacheable/cacheable_spec.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'cacheable/cache_adapters/memory_adapter_spec.rb' # Rubocop cannot tell Cache#fetch from Hash#fetch
